language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t gregvinton80/app-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gregvinton80/app-test npm test

after_success:
  - docker build -t gregvinton/multi-client ./client
  - docker build -t gregvinton/multi-nginx ./nginx
  - docker build -t gregvinton/multi-server ./server
  - docker build -t gregvinton/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push gregvinton/multi-client
  - docker push gregvinton/multi-nginx
  - docker push gregvinton/multi-server
  - docker push gregvinton/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-southeast-2
  app: multi-docker
  env: MultiDocker-env-1
  bucket_name: elasticbeanstalk-ap-southeast-2-930677577891
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
